### ISSUE TITLE
Authorization error from time to time.

### ISSUE THREAD

**Issue by vazellin** [craigchristenson/woocommerce-2checkout-api#17]
I have installed latest versions of WordPress+WooCommerce+woocommerce-2checkout-api.
My customers often have error Authorization failed, when try to pay order via 2CO API plugin. API Call Log  items have "No items selected" message. This problem happening from approximately 2 times out of 3.
How can I fix this or give you more details?
![er](https://cloud.githubusercontent.com/assets/22392295/18782940/a0dea2ce-8191-11e6-9610-224e802a0a1d.PNG)

**Comment by craigchristenson** [comment]
Hi vazellin, these logs just indicate an authorization failure on the credit card. The "No Items Selected" message just indicates that the API request was sent using the "total" instead of defining lineitems. The 2Checkout Payment API allows you to send either an itemized list of products or just the order total with an identifier. Since the cart contents are stored in woocommerce, we just pass the order total with the cart identifier. To troubleshoot these authorization failures, you will need to contact 2Checkout's tech support. They can trace each request to give more details on the card decline.

**Comment by sadi-techseed** [comment]
+1 @vazellin Did you get this issue resolved?  I've also few of our customers complaining for this.

**Comment by vazellin** [comment]
Issue not resolved ((
I have long discuss with tech support and plugin author but no success result.

**Comment by sadi-techseed** [comment]
@vazellin  We are also trying to figure it out. I'll let you know once we get to it.

Do you also have following issue with your website?
https://github.com/craigchristenson/woocommerce-2checkout-api/issues/18

**Comment by craigchristenson** [comment]
@vazellin @sadi-techseed are you still experiencing an issue here? If so please let me know so we can get it resolved.

**Comment by infopriyank** [comment]
Hi Craig,

I have same error . it suddenly occur from last two days 
this is the error
Authorization Failed: Please verify your information and try again, or try another payment method.
API call body : No Items Selected.

how to resolve this ? can you please help me ?

Regards
Priyank

**Comment by capuromeyer** [comment]
Hi Craig,

When testing my site with the sandbox from 2checkout I get the same error.

"Payment Authorization Failed: Please verify your information and try again, or try another payment method."

![image](https://cloud.githubusercontent.com/assets/13504227/26136526/2ffadf28-3a82-11e7-8b25-5583937c0b45.png)

Any clue how to fix that ?

**Comment by ZaheerAbdulwajid** [comment]
+1

**Comment by maurisaavedra-storyfeed** [comment]
+1

**Comment by dani0332** [comment]
+1

**Comment by RomanStone** [comment]
+1
