### ISSUE TITLE
Product name issue

### ISSUE THREAD

**Issue by omarmasrur** [craigchristenson/woocommerce-2checkout-api#19]
Hello Craig

Thanks for the API. I am not techie but got things to work except one area...the 2CO email that goes out does not register a Product Name (has  number) and this is the same number appearing for Merchant Id in the email. All other fields seem to have gone over to 2CO. Not sure what is causing this. 

I downloaded woocommerce and your api just 2 days back.

Any help would be greatly appreciated. tks

**Comment by craigchristenson** [comment]
Hi omarmasrur. This module passes the woocommerce cart identifier (merchant order id) to 2Checkout instead of the individual lineitem data. The email that the woocommerce system sends to your customers will have the lineitem data and the cart identifier but the 2Checkout email will only have the cart identifier.
