### ISSUE TITLE
2Checkout dashboard show "Intangible Sale  No Shipping"

### ISSUE THREAD

**Issue by misokralj** [craigchristenson/woocommerce-2checkout-api#25]
When someone order from my store, in 2co dashboard my order is marked as intangible, and I cant add tracking number. My product is tangible, so is important to add tracking number in my 2checkout dashboard.
WordPress version: 4.7.1
WooCommerce version: 2.6.11
Thanks.

**Comment by craigchristenson** [comment]
This module passes the woocommerce cart identifier (merchant order id) to 2Checkout instead of the individual lineitem data. The email that the woocommerce system sends to your customers will have the lineitem data and the cart identifier but the 2Checkout will only have the cart identifier so you will not need to mark the order as shipped. This can be done within your woocommerce cart if needed but it is not required by 2Checkout.
