### ISSUE TITLE
Notify URL input?

### ISSUE THREAD

**Issue by KoolPal** [craigchristenson/woocommerce-2checkout-api#44]
```
if ( ( 'yes' == $this->debug) && ($this->notify_url) && ($this->notify_url !=='') )
```
as the equality test alone would error if the property is undefined..

_Originally posted by @Jon007 in https://github.com/craigchristenson/woocommerce-2checkout-api/pull/32#issuecomment-399343852_

Where are you asking for this notify URL input? I cannot see this field in 2checkout API settings at all.

**Comment by Jon007** [comment]
We can't find it either, it seems to be an error in the source code.

This line in the source code causes an error when run in debug because notify_url is not set:
https://github.com/craigchristenson/woocommerce-2checkout-api/blob/master/twocheckout/wc-twocheckout.php#L366

and indeed notify_url does not seem to be used....  which may be a shame since
2Checkout does seem to have some sort of notify / IPN mechanism, sadly none of the plugins implement this (or any useful logging), not even the paid one from WooCommerce.

This, along with some of the bizarre little-documented rules implemented by 2Checkout make 2Checkout a very painful experience compared to some of the alternatives.
[phone number is mandatory for 2Checkout but optional in WooCommerce and not enforced by the plugin and not recommended for Paypal (nor advisable under European law), customers from some countries are silently unsupported (if 2Checkout is unsupported, the 2Checkout option should not be available at checkout rather than returning meaningless error), any error at all results in the same cryptic error message with no clue as to the real error - albeit that's the fault of 2Checkout not this plugin].

**Comment by KoolPal** [comment]
Thanks for your response. 

I agree with the complexity of trying to make 2checkout work. 

My experience in last 2 weeks to see **ONE** successful test transaction using sandbox and **different plugins** has been bizarre (to put it mildly).

I am waiting for a reply from 2checkout for next steps.

Having said that I realized I will have to drop this plugin as it requires my Woocommerce store to be PCI compliant. I cannot afford to add another layer of complexity to my work for now.

Thanks.

**Comment by KoolPal** [comment]
@Jon007 What Payment provider have you finally settled with? 

In case you have managed to make 2checkout work, are there any notes you can share?

Thanks.

**Comment by Jon007** [comment]
To get 2checkout working, as I recall:
- Firstly, telephone number is mandatory, if a customer tries to check out without supplying a telephone number it just doesn't work and also does not give any useful error
- Secondly, customer must be in a 2checkout supported country:  if a customer from an unsupported country tries to checkout it just doesn't work and also does not give any useful error
- some of the plugins the public key / private key stuff is the opposite order from the 2checkout admin screen so watch out for that
- the sandbox / test mode isn't as documented in most places and also has additional limitations which mean it will work for a smaller range of currencies and countries. As I recall the sandbox mode doesn't really work at all, you have to get a separate test account from the somewhat dysfunctional test site.  So due to the test limitations this can be a huge waste of time, might as well test a live payment, that'a all the counts in the end..
- if you have multicurrency store, just check/hack your plugin to pass the order currency rather than the shop currency


This isn't the place to discuss other providers but Stripe admin UI and plugin is an absolute joy to use, compared to both paypal and 2checkout.  Stripe only supports shops based in a limited range of countries though, so some shops will need other options.  But if your shop country is supported by Stripe you'd be insane not to use that.  They even do PCI for you.

**Comment by KoolPal** [comment]
@Jon007 Thanks a lot for your tips. I shall play around with them. 

So far Stripe has not yet launched in my country. I am waiting for them.

Till then I am stuck with dealing with the likes of PayPal and 2 checkout!
